name : manual_workflow

on:
  workflow_dispatch:
   inputs:
     name: 
       description: "Name"
       type: string
       default: 'test'

     age:
       description: "Age"
       type: "number"
       required: true

     Gender:
      description: "Gender"
      type: choice
      required: true
      options:
        - Female
        - Male
     
jobs:
  demo1:
   runs-on: ubuntu-latest

   steps:
     - name: Greetings
       run: echo "${{inputs.name}}"

     - name: Age
       run: echo ${{inputs.age}}
  
  
