name : manual_workflow

on:
  workflow_dispatch:
   inputs:
     name: 
       description: "Name"
       type: string
       default: 'test'

     age:
       description: "age"
       type: "number"
       required: true

jobs:
  demo1:
   runs-on: ubuntu-latest

   steps:
     - name: Greetings
       run: echo "${{inputs.name}}"

     - name: Age
       run: echo ${{inputs.age}}
  
  
