name: schedule_workflow

on:
 schedule:
   - cron: "*/5 * * * *"

jobs:
  demo3:
   runs-on: ubuntu-latest

   steps: 
     - name: Log time
       run: |
        current_date_time=$(date)
        echo "Current Date and time: $current_date_time"
